### ISSUE TITLE
`TypeError: Cannot read property 'pos' of undefined` with Mocha/npm

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js-euler#14]
I can successfully run the layout in the browser with release 1.0.0 but using npm through Mocha with the same version I get the following error:

```
  TypeError: Cannot read property 'pos' of undefined
      at insert (node_modules/cytoscape-euler/webpack:/src/euler/quadtree/index.js:206:17)
      at Object.insertBodies (node_modules/cytoscape-euler/webpack:/src/euler/quadtree/index.js:191:7)
      at tick (node_modules/cytoscape-euler/webpack:/src/euler/tick.js:22:12)
      at Layout.tick (node_modules/cytoscape-euler/webpack:/src/euler/index.js:118:20)
      at tick (node_modules/cytoscape-euler/webpack:/src/layout/tick.js:7:29)
      at multitick (node_modules/cytoscape-euler/webpack:/src/layout/tick.js:28:26)
      at _frame (node_modules/cytoscape-euler/webpack:/src/layout/index.js:108:9)
      at Layout.run (node_modules/cytoscape-euler/webpack:/src/layout/index.js:134:7)
      at Object.run (js/layout.js:15:16)
      at Context.<anonymous> (test/cytoscapeTest.js:28:12)
```

## cytoscapeTest.js (simplified)
```
import cytoscape from 'cytoscape';
import euler from 'cytoscape-euler';
cytoscape.use(euler);

var config =
{
  name: "euler",
  springLength: edge => 200,
  maxSimulationTime: 2000,
  randomize: true,
  fit:false,
  mass: node => 40,
};

describe('cytoscape', function()
{
  var cy = cytoscape({});
   ... // load graph ...
  it('apply euler layout', function()
  {
    cy.layout(config);
  });
});
```
Using the `cose` layout instead does result in an error.

To run the tests, I use `mocha --compilers js:babel-register --require isomorphic-fetch` with the following `devDependencies` in `package.json`:

```
 "babel-cli": "^6.24.1",
    "babel-preset-env": "^1.6.0",
    "babel-register": "^6.24.1",
    "chai": "^4.1.0",
    "cytoscape": "^3.1.4",
    "cytoscape-euler": "^1.0.0",
    "es6-promise": "^4.1.1",
    "eslint": "^4.2.0",
    "isomorphic-fetch": "^2.2.1",
    "mocha": "^3.4.2"

```
## .babelrc.json
```
{
  "presets":
  [[
    "env", {
      "targets": {
        "chrome": 52,
        "browsers": ["Firefox 49", "Edge 12","Chrome 53", "Opera 41", "Safari 10"]
      },
      "useBuiltIns": true
      }]]
}                                                                                                                     
~                
```

P.S.: Using cytoscape.js 3.1.5 instead of 3.1.4 does not fix the error.

**Comment by maxkfranz** [comment]
I was able to run it with the same options in node@6, cytoscape@3.2.3

I notice you're missing .layout().run()
